"""auto-vote

Revision ID: 3ce0f1c9e0b1
Revises: aa6804ac6b70
Create Date: 2022-05-12 23:43:13.263456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ce0f1c9e0b1'
down_revision = 'aa6804ac6b70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
